GET http://0.0.0.0:8025/hello/2021
 
 
 
 
###
POST http://0.0.0.0:8025/users/
Content-Type: application/json
 
{
    "name": "Mario Ix",
    "email": "mhadaniya1ix@email.com",
    "password": "12345"
}
 
 
 
 
###
GET http://127.0.0.1:8082/users/
 
 
 
###
GET http://127.0.0.1:8082/users/6
 
 
 
###
POST http://127.0.0.1:8082/users/
Content-Type: application/json
 
{
    "name": "Xiao Yu",
    "email": "xiao.yu@edu.unifil.br",
    "password": "12345"
}
 
 
###
GET http://127.0.0.1:8082/measures/
 
 
###
GET http://127.0.0.1:8082/users/6/measures/
 
 
###
POST http://127.0.0.1:8082/users/2/measures/
Content-Type: application/json
 
{
    "height": "178",
    "weight": "60",
    "neck": "70",
    "chest": "70",
    "biceps": "70",
    "waist": "70",
    "thighs": "70",
    "calf": "70"
}
 
 
 
 
###
PUT http://127.0.0.1:8082/users/
Content-Type: application/json
 
{
    "name": "Xiao Yu",
    "email": "xiao.yu@edu.unifil.br",
    "birth_date": "2000-04-18"
}
 
 
 
###
POST http://127.0.0.1:8082/
Content-Type: application/json
 
{
    "name": "Xiao Yu",
    "email": "xiao.yu@edu.unifil.br"
}
 
 
 
 
 
###
PUT http://127.0.0.1:8082/users/2
Content-Type: application/json
 
{
    "name": "Nome",
    "price": 1
}
 
###
DELETE http://127.0.0.1:8082/users/2
 
